// Code generated by protoc-gen-go.
// source: config.proto
// DO NOT EDIT!

/*
Package protomsg is a generated protocol buffer package.

It is generated from these files:
	config.proto
	handshake.proto

It has these top-level messages:
	Config
*/
package protomsg

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Config struct {
	ServerName       *string        `protobuf:"bytes,1,opt,name=server_name,def=nest2go" json:"server_name,omitempty"`
	LogDir           *string        `protobuf:"bytes,2,opt,name=log_dir,def=." json:"log_dir,omitempty"`
	OpenPorts        []*Config_Port `protobuf:"bytes,3,rep,name=open_ports" json:"open_ports,omitempty"`
	Apps             []*Config_App  `protobuf:"bytes,4,rep,name=apps" json:"apps,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}

const Default_Config_ServerName string = "nest2go"
const Default_Config_LogDir string = "."

func (m *Config) GetServerName() string {
	if m != nil && m.ServerName != nil {
		return *m.ServerName
	}
	return Default_Config_ServerName
}

func (m *Config) GetLogDir() string {
	if m != nil && m.LogDir != nil {
		return *m.LogDir
	}
	return Default_Config_LogDir
}

func (m *Config) GetOpenPorts() []*Config_Port {
	if m != nil {
		return m.OpenPorts
	}
	return nil
}

func (m *Config) GetApps() []*Config_App {
	if m != nil {
		return m.Apps
	}
	return nil
}

type Config_Port struct {
	Addr             *string `protobuf:"bytes,1,req,name=addr" json:"addr,omitempty"`
	TlsCertFile      *string `protobuf:"bytes,2,opt,name=tls_cert_file" json:"tls_cert_file,omitempty"`
	TlsKeyFile       *string `protobuf:"bytes,3,opt,name=tls_key_file" json:"tls_key_file,omitempty"`
	RsaPrivatePem    *string `protobuf:"bytes,4,opt,name=rsa_private_pem" json:"rsa_private_pem,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Config_Port) Reset()         { *m = Config_Port{} }
func (m *Config_Port) String() string { return proto.CompactTextString(m) }
func (*Config_Port) ProtoMessage()    {}

func (m *Config_Port) GetAddr() string {
	if m != nil && m.Addr != nil {
		return *m.Addr
	}
	return ""
}

func (m *Config_Port) GetTlsCertFile() string {
	if m != nil && m.TlsCertFile != nil {
		return *m.TlsCertFile
	}
	return ""
}

func (m *Config_Port) GetTlsKeyFile() string {
	if m != nil && m.TlsKeyFile != nil {
		return *m.TlsKeyFile
	}
	return ""
}

func (m *Config_Port) GetRsaPrivatePem() string {
	if m != nil && m.RsaPrivatePem != nil {
		return *m.RsaPrivatePem
	}
	return ""
}

type Config_App struct {
	TypeName         *string  `protobuf:"bytes,1,req,name=type_name" json:"type_name,omitempty"`
	IdName           *string  `protobuf:"bytes,2,req,name=id_name" json:"id_name,omitempty"`
	SetupString      *string  `protobuf:"bytes,3,opt,name=setup_string,def=" json:"setup_string,omitempty"`
	ListenPortAddr   []string `protobuf:"bytes,4,rep,name=listen_port_addr" json:"listen_port_addr,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Config_App) Reset()         { *m = Config_App{} }
func (m *Config_App) String() string { return proto.CompactTextString(m) }
func (*Config_App) ProtoMessage()    {}

func (m *Config_App) GetTypeName() string {
	if m != nil && m.TypeName != nil {
		return *m.TypeName
	}
	return ""
}

func (m *Config_App) GetIdName() string {
	if m != nil && m.IdName != nil {
		return *m.IdName
	}
	return ""
}

func (m *Config_App) GetSetupString() string {
	if m != nil && m.SetupString != nil {
		return *m.SetupString
	}
	return ""
}

func (m *Config_App) GetListenPortAddr() []string {
	if m != nil {
		return m.ListenPortAddr
	}
	return nil
}

func init() {
}
